/* Generated by tools/build.js — do not edit. Source of truth: config/story.js */
export const data = /*__STORY_DATA__*/ null;

function pos(d, sum, isMobile, isTablet, innerHeight) {
  if (!d) return 0;
  const n = isMobile ? 2 : 1;
  return sum(d.s || 0)
    + (d.base || 0)
    + (d.half || 0) / n
    + (isMobile ? (d.mobile || 0) : 0)
    + (isTablet ? (d.tablet || 0) : 0)
    + (innerHeight < 850 ? (d.short || 0) : 0);
}

function resolve(item, sum, isMobile, tabletRef, heightRef) {
  const isTablet = tabletRef && typeof tabletRef === 'object' && 'value' in tabletRef
    ? tabletRef.value : Boolean(tabletRef);
  const h = heightRef && typeof heightRef === 'object' && 'value' in heightRef
    ? heightRef.value : Number(heightRef) || 0;
  const out = {
    className: item.className || '',
    scrollStart: pos(item.at, sum, isMobile, isTablet, h),
    scrollEnd: pos(item.to, sum, isMobile, isTablet, h),
    scrollStart2: pos(item.out, sum, isMobile, isTablet, h),
    scrollEnd2: pos(item.gone, sum, isMobile, isTablet, h),
    debug: Boolean(item.debug),
  };
  if (item.toTop !== undefined) out.toTop = item.toTop;
  return out;
}

/** Text blocks (SmallTextNew / BigTextNew / LinesText). */
export function blocks(list, sum, isMobile, tabletRef, heightRef) {
  return list.map((item) => {
    const o = resolve(item, sum, isMobile, tabletRef, heightRef);
    o.text = item.html;
    return o;
  });
}

/**
 * Case hotspots (CaseHover), rendered through a Teleport.
 * CaseHover only declares content/link/id props — the scrollStart/scrollEnd and
 * mode keys carried by the original array were never read, so they are gone.
 */
export function cases(list) {
  return list.map((item, i) => ({
    className: item.className || '',
    content: item.html,
    link: item.url || '',
    id: item.crystal || `crystal${i}`,
  }));
}
